# Generated by Django 6.0.4 on 2026-05-12 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oipah', '0002_sectoragricul'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_land', models.CharField(max_length=100, null=True)),
                ('statut_land', models.CharField(max_length=100, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('sub_prefecture', models.CharField(max_length=100, null=True)),
                ('quater', models.CharField(max_length=100, null=True)),
                ('gps', models.CharField(max_length=100, null=True)),
                ('land_ownership', models.CharField(blank=True, max_length=255, null=True)),
                ('acd_number', models.CharField(blank=True, max_length=255, null=True)),
                ('type_ground', models.CharField(blank=True, max_length=255, null=True)),
                ('source_water', models.CharField(blank=True, max_length=255, null=True)),
                ('gate_owner', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oipah.sectoragricul')),
                ('oipah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oipah.oipahattribute')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
