# Generated by Django 6.0.4 on 2026-05-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotLand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plotland',
            old_name='gate_owner',
            new_name='date_owner',
        ),
        migrations.RenameField(
            model_name='plotland',
            old_name='user',
            new_name='owner_land',
        ),
    ]
