# Generated by Django 6.0.4 on 2026-05-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotLand', '0002_rename_gate_owner_plotland_date_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotland',
            name='code_land',
        ),
    ]
