# Generated by Django 6.0.4 on 2026-05-06 15:20

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('oipah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='oipah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oipah.oipahattribute'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=0.8, size=[1920, 1080], upload_to='Photos de profil'),
        ),
        migrations.AddField(
            model_name='user',
            name='oipah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oipah.oipahattribute'),
        ),
    ]
