# Generated by Django 6.0.4 on 2026-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission_oipah_user_image_user_oipah'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nber_doc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type_doc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
