# Generated by Django 6.0.4 on 2026-05-06 15:20

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OipahAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('rccm', models.CharField(blank=True, max_length=100, null=True)),
                ('niu', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone', models.CharField(db_index=True, max_length=50, null=True)),
                ('devise', models.CharField(blank=True, max_length=50, null=True)),
                ('itemNber', models.PositiveIntegerField(default=0)),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=95, scale=0.8, size=[1920, 1080], upload_to='logos')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
