# Generated by Django 6.0.4 on 2026-05-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oipah', '0002_sectoragricul'),
    ]

    operations = [
        migrations.AddField(
            model_name='oipahattribute',
            name='rate_dev',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
