# Generated by Django 6.0.4 on 2026-05-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oipah', '0004_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='model_vehicle',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='registration',
            new_name='plate',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
