# Generated by Django 6.0.4 on 2026-06-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oipah', '0005_rename_model_vehicle_vehicles_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='owner',
        ),
    ]
