# Generated by Django 6.0.4 on 2026-05-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grantors', '0008_subsidy_static_amount'),
        ('oipah', '0002_sectoragricul'),
        ('plotLand', '0003_remove_plotland_code_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_project', models.CharField(blank=True, max_length=255, null=True)),
                ('current_statut', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_per_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('nber_date', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oipah.sectoragricul')),
                ('grantor', models.ManyToManyField(blank=True, to='grantors.grantors')),
                ('plot_land', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotLand.plotland')),
            ],
        ),
    ]
