# Generated by Django 6.0.4 on 2026-05-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0010_subsidy_rest_amnt'),
        ('oipah', '0002_sectoragricul'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='nber_date',
            new_name='nber_days',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='grantor',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='modeExecution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='oipah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oipah.oipahattribute'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='subsidies',
            field=models.ManyToManyField(blank=True, to='grantors.subsidy'),
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='filiere',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='filiere',
            field=models.ManyToManyField(null=True, to='oipah.sectoragricul'),
        ),
    ]
