# Generated by Django 6.0.4 on 2026-05-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_nber_date_projectmodel_nber_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='subsidies',
        ),
    ]
