# Generated by Django 6.0.4 on 2026-05-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0010_subsidy_rest_amnt'),
        ('project', '0003_remove_projectmodel_subsidies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_subsidies', to='project.projectmodel')),
                ('subsidy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_projects', to='grantors.subsidy')),
            ],
            options={
                'db_table': 'project_subsidy',
            },
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='subsidies',
            field=models.ManyToManyField(blank=True, through='project.ProjectSubsidy', to='grantors.subsidy'),
        ),
    ]
