# Generated by Django 6.0.4 on 2026-05-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0010_subsidy_rest_amnt'),
        ('project', '0004_projectsubsidy_projectmodel_subsidies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='subsidies',
            field=models.ManyToManyField(null=True, through='project.ProjectSubsidy', to='grantors.subsidy'),
        ),
        migrations.CreateModel(
            name='HistorikProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectmodel')),
            ],
        ),
    ]
