# Generated by Django 6.0.4 on 2026-05-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectmodel_subsidies_historikproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historikproject',
            old_name='status',
            new_name='statut_project',
        ),
    ]
