# Generated by Django 6.0.4 on 2026-05-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oipah', '0002_sectoragricul'),
        ('project', '0006_rename_status_historikproject_statut_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_entrepreneur', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('oipah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oipah.oipahattribute')),
            ],
        ),
    ]
