# Generated by Django 6.0.4 on 2026-06-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_commissionproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
