# Generated by Django 6.0.4 on 2026-06-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectmodel_driver_projectmodel_harverst_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcharge',
            old_name='date_charge',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='projectcharge',
            old_name='title',
            new_name='label',
        ),
    ]
