# Generated by Django 6.0.4 on 2026-05-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oipah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grantors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('type_grantor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('oipah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oipah.oipahattribute')),
            ],
        ),
    ]
