# Generated by Django 6.0.4 on 2026-05-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantors',
            old_name='county',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='grantors',
            old_name='type_grantor',
            new_name='type_donor',
        ),
    ]
