# Generated by Django 6.0.4 on 2026-05-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0003_subsidy'),
        ('oipah', '0002_sectoragricul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidy',
            name='filiere',
        ),
        migrations.AddField(
            model_name='subsidy',
            name='filiere',
            field=models.ManyToManyField(blank=True, null=True, to='oipah.sectoragricul'),
        ),
    ]
