# Generated by Django 6.0.4 on 2026-05-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0004_remove_subsidy_filiere_subsidy_filiere'),
        ('oipah', '0002_sectoragricul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='filiere',
            field=models.ManyToManyField(blank=True, to='oipah.sectoragricul'),
        ),
    ]
