# Generated by Django 6.0.4 on 2026-05-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0005_alter_subsidy_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyPatial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced_amnt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subsidy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grantors.subsidy')),
            ],
        ),
    ]
