# Generated by Django 6.0.4 on 2026-05-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0006_subsidypatial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidypatial',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
