# Generated by Django 6.0.4 on 2026-05-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0007_subsidypatial_received_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidy',
            name='static_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
