# Generated by Django 6.0.4 on 2026-05-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0008_subsidy_static_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidy',
            old_name='static_amount',
            new_name='dynamic_amount',
        ),
    ]
