# Generated by Django 6.0.4 on 2026-05-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0009_rename_static_amount_subsidy_dynamic_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidy',
            name='rest_amnt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
