# Generated by Django 6.0.4 on 2026-05-31 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantors', '0010_subsidy_rest_amnt'),
        ('oipah', '0004_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission_Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('advanced_amnt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status_comm', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('oipah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oipah.oipahattribute')),
                ('subsidy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grantors.subsidy')),
            ],
        ),
    ]
